### ISSUE TITLE
Please re-license under a more liberal license

### ISSUE THREAD

**Issue by rsmarples** [obaydmerz/powerjs#5]
Please consider using a different license for this great product!
First and foremost, this is a library which is designed to be used by other applications.

I would love to use this in my closed source Electron application, but neither the GPL nor LGPL would allow this.
Please consider any of the BSD, ISC, MIT or Apache licenses as used by the vast majority of the NPM world.

**Comment by xipid** [comment]
Re-licensed!

**Comment by rsmarples** [comment]
Many many thanks!
